branches:
    only:
        - master
        - ppc64le_support
language: ruby
services:
    - docker

env:
  global:
    - IMAGE=murilofv/jq
    - NV=`curl --silent "https://raw.githubusercontent.com/alpinelinux/aports/master/main/jq/APKBUILD" | grep pkgver= | sed 's/pkgver=//g'`

stages:
  - Arch-Build
  - Manifest-Release

jobs:
  include:
    - stage: Arch-Build
      arch: amd64
      os: linux
      script:
        - RELEASE=0
        - docker pull $IMAGE:$NV-$TRAVIS_CPU_ARCH || RELEASE=1
        - make build IMAGE=$IMAGE TAG=$NV || exit 1
      after_success:
        - "[ ${RELEASE} == 1 ] && (make release DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS IMAGE=$IMAGE TAG=$NV)"

    - stage: Arch-Build
      arch: ppc64le
      os: linux
      script:
        - RELEASE=0
        - docker pull $IMAGE:$NV-$TRAVIS_CPU_ARCH || RELEASE=1
        - make build IMAGE=$IMAGE TAG=$NV || exit 1
      after_success:
        - "[ ${RELEASE} == 1 ] && (make release DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS IMAGE=$IMAGE TAG=$NV)"

    - stage: Manifest-Release
      arch: amd64
      os: linux
      script:
        - export DOCKER_CLI_EXPERIMENTAL=enabled
        - MANIFEST_RELEASE=0
        - docker pull $IMAGE:$NV || MANIFEST_RELEASE=1
        - "[ ${MANIFEST_RELEASE} == 1 ] && (make release-manifest DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS IMAGE=$IMAGE TAG=$NV)"
